# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89327f3cfb432e84faf17d084cdf8df32a158f11ca2b09012b4ff48e30f2fa80a7828d0652ab86e81e71c9fa81268ee6fac12b42e38293a3c79516bc7efeb84e

test:
  secret_key_base: a076e9f2664f3ce3747e632c0609ba9ee1341d35e2ea1d2bf809dc964b3a826a6a76104a6911c94e24c06be334ae3c0ed392be58d4f24e9cab5a44ca38e9f941

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
